name: Grab latest tutorials

on:
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "siavash.ghelichkhan@anu.edu.au"
          git config --global user.name "Sia Ghelichkhan"

      - name: Get latest successful workflow run from tutorials
        id: get_run
        run: |
          response=$(curl -s \
            -H "Authorization: token ${{ secrets.ACCESS_KEY }}" \
            "https://api.github.com/repos/water-course/tutorials/actions/workflows/jupytext-conversion.yml/runs?status=success&per_page=1")
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
          echo $run_id
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Get artifact download URL
        id: get_artifact
        run: |
          artifacts=$(curl -s \
            -H "Authorization: token ${{ secrets.ACCESS_KEY }}" \
            "https://api.github.com/repos/water-course/tutorials/actions/runs/${{ steps.get_run.outputs.run_id }}/artifacts")
          echo "Artifacts response: $artifacts"
          download_url=$(echo "$artifacts" | jq -r '.artifacts[] | select(.name=="ready") | .archive_download_url')
          if [ -z "$download_url" ]; then
            echo "Error: No download URL found for artifact 'ready'."
            exit 1
          fi
          echo "download_url=$download_url" >> $GITHUB_OUTPUT

      - name: Download and unzip artifact
        run: |
          curl -L -H "Authorization: token ${{ secrets.ACCESS_KEY }}" \
            -o ready.zip "${{ steps.get_artifact.outputs.download_url }}"
          unzip ready.zip

      - name: List downloaded content
        run: find ./

      - name: Add and commit .ipynb files and image directory
        run: |
          # Add all .ipynb files except those ending with _solution.ipynb
          git add $(find . -name "*.ipynb" ! -name "*_solution.ipynb")
          # Add the image directory
          git add image/
          # Commit the changes
          git commit -m "Add .ipynb files and image directory"

      - name: Push changes
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: |
          git remote set-url origin https://x-access-token:${ACCESS_KEY}@github.com/water-course/colab-tutorials.git
          git config --global user.email "siavash.ghelichkhan@anu.edu.au"
          git config --global user.name "Sia Ghelichkhan"
          git push origin main